version: '3.4'

networks:
  br-blog:
    driver: bridge

services:

  ghost:
    image: ghost
    restart: always
    container_name: ghost
    networks:
      - br-blog
    expose:
      - "2368"
    environment:
      - database__client=mysql
      - database__connection__host=mysql
      - database__connection__user=root
      - database__connection__password=6omtOILMUgWirwbH
      - database__connection__database=ghost
    volumes:
      - /data/ghost:/var/lib/ghost

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    networks:
      - br-blog
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=6omtOILMUgWirwbH
    volumes:
      - /data/mysql:/var/lib/mysql

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    networks:
      - br-blog
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/nginx:/etc/nginx
      - /data/logs/nginx:/var/log/nginx
      - /data/certs:/etc/ssl/certs
